#!/bin/bash
alloc_id=<Allocation ID of the Elastc IP>
instance_id=$(curl http://169.254.169.254/latest/meta-data/instance-id)
region=$(curl --silent http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region)
aws ec2 associate-address --allocation-id $alloc_id --instance-id $instance_id --allow-reassociation --region $region